In [ ]:
import numpy as np

In [ ]:
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)
numbers
# array([[ 5, 6,  8, 10, 12, 14],
#        [16, 18, 20, 22, 24, 26],
#        [28, 30, 32, 34, 36, 38],
#        [40, 42, 44, 46, 48, 50]])



In [ ]:
mask = numbers % 4 == 0
mask
# array([[False, False,  True, False,  True, False],
#        [ True, False,  True, False,  True, False],
#        [ True, False,  True, False,  True, False],
#        [ True, False,  True, False,  True, False]])

In [ ]:
numbers[mask]
# array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [ ]:
by_four = numbers[numbers % 4 == 0]
by_four
# array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])