### Transposing examples:

In [ ]:
import numpy as np

In [ ]:
a = np.array([
 [1, 2],
 [3, 4],
 [5, 6]
 ])
a

In [ ]:
a.T
# array([[1, 3, 5],
#        [2, 4, 6]])

In [ ]:
a.transpose()
# array([[1, 3, 5],
#        [2, 4, 6]])

### Sorting examples:

In [ ]:
data = np.array([
[7, 1, 4],
[8, 6, 5],
[1, 2, 3]
])
data

In [ ]:
np.sort(data)
# array([[1, 4, 7],
#        [5, 6, 8],
#        [1, 2, 3]])

In [ ]:
np.sort(data, axis=None)
# array([1, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.sort(data, axis=0)
# array([[1, 1, 3],
#        [7, 2, 4],
#        [8, 6, 5]])

### Concatenation examples:

In [ ]:
a = np.array([
[4, 8],
[6, 1]
])
a

In [ ]:
b = np.array([
[3, 5],
[7, 2],
])
b

In [ ]:
np.hstack((a, b))
# array([[4, 8, 3, 5],
#        [6, 1, 7, 2]])

In [ ]:
np.vstack((b, a))
# array([[3, 5],
#        [7, 2],
#        [4, 8],
#        [6, 1]])

In [ ]:
np.concatenate((a, b))
# array([[4, 8],
#        [6, 1],
#        [3, 5],
#        [7, 2]])

In [ ]:
np.concatenate((a, b), axis=None)
# array([4, 8, 6, 1, 3, 5, 7, 2])