In [1]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Common RNN Notations
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

# Create some random data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [3]:
# Defining our model
M = 5 # number of hidden units
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

# Get the output
Yhat = model.predict(X)
print(Yhat)


[[ 0.60632676 -0.527643  ]]


In [4]:
#Print the model summary
model.summary()

model.layers[1].get_weights()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


[array([[ 0.6694328 ,  0.17750007, -0.46753207,  0.01913708,  0.76028055],
        [ 0.4778499 , -0.16163254,  0.19068545,  0.31051928,  0.27357215],
        [-0.08221358,  0.07473624,  0.21347195,  0.14314538,  0.59074193]],
       dtype=float32),
 array([[ 0.07403183, -0.37959582, -0.66818696,  0.5601464 ,  0.30031374],
        [ 0.9212898 ,  0.17158173, -0.18981485, -0.2792261 ,  0.08825   ],
        [-0.10548763,  0.63829714,  0.11640278,  0.1951016 ,  0.7278975 ],
        [ 0.00731886,  0.620885  , -0.28377652,  0.40672988, -0.60703367],
        [-0.36682874,  0.18315378, -0.6507056 , -0.6362192 ,  0.06081746]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [6]:
# First output is input > hidden
# Second output is hidden > hidden
# Third output is bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

a,b=model.layers[2].get_weights()
print(a,b)

(3, 5) (5, 5) (5,)
[[ 0.86694455  0.46330094]
 [-0.77970386 -0.25613248]
 [-0.35431463 -0.8113095 ]
 [-0.8408678   0.803313  ]
 [-0.815622   -0.90647507]] [0. 0.]


In [7]:
# We will do manual calculation of RNN
# Assigning Weight variables

Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)
  
  # important: assign h to h_last
  h_last = h

# print the final output
print(Yhats[-1])

[ 0.60632697 -0.52764312]
