<b>SEIS763-02-Machine Learning <br>
Assignment1  <br>                                                                                               
Shivali Dalmia</b>

In [154]:
#Importing required libraries
import numpy as np

1) Create a vector of size 15 having third element (i.e. position 2) set to 1 and rest of the elements should be zero.

In [155]:
#Horizontal vector
hvector = np.zeros((15),dtype=int)
hvector[2] = 1
print("Horizontal vector")
print(hvector)

print("")

#Vertical vector
vvector = np.zeros((15,1),dtype=int)
vvector[2,0] = 1
print("Vertical Vector")
print(vvector)

Horizontal vector
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]

Vertical Vector
[[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


2) Create a vector with values ranging from 21 to 30.

In [156]:
#Vector with values ranging from 21 to 30.
vector2 = np.arange(21,31)
print(vector2)

[21 22 23 24 25 26 27 28 29 30]


3) Reverse the order of elements in the vector in question 2. That is, the previous last element should be the first one now.

In [157]:
#Reversing the order elements in vector2.
vector2 = np.flip(vector2,axis=0)
print(vector2)

[30 29 28 27 26 25 24 23 22 21]


4) Define a vector with values ranging from 1 to 12. Now define a 4x3 matrix to store elements from the vector you have defined. That is, first 3 elements of the vector should be row 1 of the matrix, next 3 should be row 2, and so on.

In [158]:
#Creating a matrix with values from 1 to 12.
vector4 = np.arange(1,13)
matrix4 = vector4.reshape((4,3))
print(matrix4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


5) Consider the 4x3 matrix from question 4. Add 100 to all values that are greater than equal to 3 and less than equal to 8.

In [159]:
#Adding 100 to values in matrix4 where 3<=number<=8.
filter1 = np.logical_and(matrix4 >= 3, matrix4 <=8)
matrix4[filter1] += 100
print(matrix4)

[[  1   2 103]
 [104 105 106]
 [107 108   9]
 [ 10  11  12]]


6) Consider the vector x = [1, 0, 6, 9, 10, 0]. Print the indices of non-zero elements.

In [160]:
#Get indices of non zero elements
x=np.array([1,0,6,9,10,0])
indices = np.where(x != 0)
print(indices)

(array([0, 2, 3, 4], dtype=int64),)


7) Define a 6x3 matrix with random values. Normalize this matrix by subtracting the mean (of the column) and dividing by the standard deviation (of the column).

In [161]:
#Creating a 6X3 matrix with random 18 values.
matrix7 = np.random.randint(20,size=(6,3))
print("Matrix is")
print(matrix7)
print()

#Calculating column wise mean
column_mean = matrix7.mean(axis=0)
print("Column wise Mean")
print(column_mean)
print()

#Calculating std deviation column wise
column_sd = matrix7.std(axis=0)
print("Column wise SD")
print(column_sd)
print()

#Normalizing matrix7 by subtracting column mean and dividing by column_sd
matrix7 = matrix7 - column_mean
matrix7 = matrix7 / column_sd
print("Normalized matrix is")
print(matrix7)

Matrix is
[[ 2 18 14]
 [19  4  4]
 [ 5 18  0]
 [ 9 19  9]
 [19  5  1]
 [10 19 18]]

Column wise Mean
[10.66666667 13.83333333  7.66666667]

Column wise SD
[6.44635987 6.61857655 6.64997911]

Normalized matrix is
[[-1.34442799  0.62954121  0.95238394]
 [ 1.29271922 -1.48571725 -0.55138018]
 [-0.87904907  0.62954121 -1.15288583]
 [-0.25854384  0.7806311   0.20050188]
 [ 1.29271922 -1.33462736 -1.00250941]
 [-0.10341754  0.7806311   1.55388959]]


8) Define a 3x4 matrix with random values. Define a 4x3 matrix with random values. Multiply the two matrices.

In [162]:
#Creating matrix1 with random values
matrix8_1 = np.random.randint(12,size=(3,4))
print("Matrix 1 is")
print(matrix8_1)
print()

#Creating matrix2 with random values
matrix8_2 = np.random.randint(12,size=(4,3))
print("Matrix 2 is")
print(matrix8_1)
print()

#Printing dot product of two matrix
print("Result")
print(np.dot(matrix8_1,matrix8_2))

Matrix 1 is
[[ 3  2  3  4]
 [ 2 11  5  6]
 [ 0  7  1  3]]

Matrix 2 is
[[ 3  2  3  4]
 [ 2 11  5  6]
 [ 0  7  1  3]]

Result
[[ 65  23  65]
 [139  40 103]
 [ 64  12  35]]


9) Define a 3x3 identity matrix.

In [163]:
#Defining 3X3 identity matrix
matrix9 = np.eye(3,3,dtype=int)
print(matrix9)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


10) Define a 3x3 matrix A with random values. Invert the matrix A, let’s call this B. Multiply matrices A and B.

In [164]:
#Defining matrix A with random values
A = np.random.randint(9,size=(3,3))
print("Matrix A is")
print(A)
print()

#Inverting matrix A
B = np.linalg.inv(A)
print("Matrix B is")
print(B)
print()

#Dot product of A.B
result = np.dot(A,B)
print("Result is")
print(result)

Matrix A is
[[8 6 8]
 [3 3 4]
 [3 5 8]]

Matrix B is
[[ 5.00000000e-01 -1.00000000e+00  5.55111512e-17]
 [-1.50000000e+00  5.00000000e+00 -1.00000000e+00]
 [ 7.50000000e-01 -2.75000000e+00  7.50000000e-01]]

Result is
[[ 1.00000000e+00  0.00000000e+00 -8.88178420e-16]
 [-4.44089210e-16  1.00000000e+00 -4.44089210e-16]
 [ 0.00000000e+00 -3.55271368e-15  1.00000000e+00]]


11) Load the dataset into a pandas dataframe and display the first 5 lines of the dataset along with the column headings. Note that the data does not come along with the column headings, so you should be adding that to the data frame.

In [165]:
import pandas as pd

In [166]:
#Reading people dataset
people = pd.read_csv("people.csv")

#Adding column names
people.columns = ['firstname', 'lastname', 'age', 'company name', 'street name', 'city', 'county', 'state', 'zipcode', 'phone number','email', 'url']

#Print first 5 rows
people.head()

firstname     lastname   age                    company name  \
0     Arminda       Parvis  22.0                      Newtec Inc   
1    Herminia  Nicolozakes  59.0  Sea Island Div Of Fstr Ind Inc   
2  Christiane   Eschberger  71.0              Casco Services Inc   
3      Helene  Rodenberger  30.0  Bailey Transportation Prod Inc   
4     Regenia      Kannady   NaN   Ken Jeter Store Equipment Inc   

            street name        city    county state  zipcode  phone number  \
0        1 Huntwood Ave     Phoenix  Maricopa    AZ  85017.0  602-906-9419   
1       4 58th St #3519  Scottsdale  Maricopa    AZ  85254.0  602-954-5141   
2  96541 W Central Blvd     Phoenix  Maricopa    AZ  85034.0  602-390-4944   
3       347 Chestnut St      Peoria  Maricopa    AZ  85381.0  623-461-8551   
4         10759 Main St  Scottsdale  Maricopa    AZ  85260.0  480-726-1280   

                             email                                         url  
0               arminda@parvis.com                    http://www.newtecinc.com  
1         herminia@nicolozakes.org     http://www.seaislanddivoffstrindinc.com  
2  christiane.eschberger@yahoo.com             http://www.cascoservicesinc.com  
3                   helene@aol.com  http://www.baileytransportationprodinc.com  
4          regenia.kannady@cox.net    http://www.kenjeterstoreequipmentinc.com

12) Drop the county column.

In [167]:
#Dropping county column from people dataset
people.drop('county',axis=1,inplace=True)
people.head()

firstname     lastname   age                    company name  \
0     Arminda       Parvis  22.0                      Newtec Inc   
1    Herminia  Nicolozakes  59.0  Sea Island Div Of Fstr Ind Inc   
2  Christiane   Eschberger  71.0              Casco Services Inc   
3      Helene  Rodenberger  30.0  Bailey Transportation Prod Inc   
4     Regenia      Kannady   NaN   Ken Jeter Store Equipment Inc   

            street name        city state  zipcode  phone number  \
0        1 Huntwood Ave     Phoenix    AZ  85017.0  602-906-9419   
1       4 58th St #3519  Scottsdale    AZ  85254.0  602-954-5141   
2  96541 W Central Blvd     Phoenix    AZ  85034.0  602-390-4944   
3       347 Chestnut St      Peoria    AZ  85381.0  623-461-8551   
4         10759 Main St  Scottsdale    AZ  85260.0  480-726-1280   

                             email                                         url  
0               arminda@parvis.com                    http://www.newtecinc.com  
1         herminia@nicolozakes.org     http://www.seaislanddivoffstrindinc.com  
2  christiane.eschberger@yahoo.com             http://www.cascoservicesinc.com  
3                   helene@aol.com  http://www.baileytransportationprodinc.com  
4          regenia.kannady@cox.net    http://www.kenjeterstoreequipmentinc.com

13) Keep only those rows that have a minimum of 4 values, otherwise delete them.

In [168]:
#Dropping rows with less than 4 values
people.dropna(thresh=4,inplace=True)
people.shape

(108, 11)

14) Delete rows with email missing.

In [169]:
#Dropping all rows with no email value
people.dropna(subset=['email'],inplace=True)
people.shape

(105, 11)

15) Impute the missing values in age with the mean of the column.

In [170]:
#Dealing with missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=float("nan"), strategy='mean')
imputer.fit(people[['age']])
people['age']= imputer.transform(people[['age']]).ravel()  #ravel() - returns a flattened 1D array

16) Perform one hot encoding for the state column.

In [171]:
#Checking for Mssing values in state column
print("Missing values in state column")
print(people['state'].isna().sum())
print()

print("Frequency count of different states")
print(people['state'].value_counts())
print()

#Replacing missing value in state with most frequent value i.e. CA
people['state'].fillna('CA',inplace=True)

print("Missing values in state column after replacement")
print(people['state'].isna().sum())

Missing values in state column
1

Frequency count of different states
CA    68
FL    28
AZ     8
Name: state, dtype: int64

Missing values in state column after replacement
0


In [172]:
#Transforming state column using OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
col_trans = make_column_transformer((OneHotEncoder(), [6]), remainder='passthrough')
people = col_trans.fit_transform(people)
people = pd.DataFrame(people)

In [173]:
#Viewing final people data frame
people

0    1    2           3            4          5   \
0    1.0  0.0  0.0     Arminda       Parvis       22.0   
1    1.0  0.0  0.0    Herminia  Nicolozakes       59.0   
2    1.0  0.0  0.0  Christiane   Eschberger       71.0   
3    1.0  0.0  0.0      Helene  Rodenberger       30.0   
4    1.0  0.0  0.0     Regenia      Kannady  49.714286   
..   ...  ...  ...         ...          ...        ...   
100  0.0  0.0  1.0     Sharika        Eanes       49.0   
101  0.0  0.0  1.0    Nickolas       Juvera  49.714286   
102  0.0  0.0  1.0     Shawnda         Yori       42.0   
103  0.0  0.0  1.0      Jovita         Oles       80.0   
104  0.0  0.0  1.0    Chauncey       Motley       57.0   

                                 6                       7              8   \
0                        Newtec Inc          1 Huntwood Ave        Phoenix   
1    Sea Island Div Of Fstr Ind Inc         4 58th St #3519     Scottsdale   
2                Casco Services Inc    96541 W Central Blvd        Phoenix   
3    Bailey Transportation Prod Inc         347 Chestnut St         Peoria   
4     Ken Jeter Store Equipment Inc           10759 Main St     Scottsdale   
..                              ...                     ...            ...   
100                  Maccani & Delp     75698 N Fiesta Blvd        Orlando   
101               United Oil Co Inc     177 S Rider Trl #52  Crystal River   
102          Fiorucci Foods Usa Inc  50126 N Plankinton Ave       Longwood   
103            Pagano, Philip G Esq            8 S Haven St  Daytona Beach   
104      Affiliated With Travelodge          63 E Aurora Dr        Orlando   

          9             10                               11  \
0    85017.0  602-906-9419               arminda@parvis.com   
1    85254.0  602-954-5141         herminia@nicolozakes.org   
2    85034.0  602-390-4944  christiane.eschberger@yahoo.com   
3    85381.0  623-461-8551                   helene@aol.com   
4    85260.0  480-726-1280          regenia.kannady@cox.net   
..       ...           ...                              ...   
100  32806.0  407-312-1691            sharika.eanes@aol.com   
101  34429.0  352-598-8301          nickolas_juvera@cox.net   
102  32750.0  407-538-5106           shawnda.yori@yahoo.com   
103  32114.0  386-248-4118                  joles@gmail.com   
104  32804.0  407-413-4842          chauncey_motley@aol.com   

                                             12  
0                      http://www.newtecinc.com  
1       http://www.seaislanddivoffstrindinc.com  
2               http://www.cascoservicesinc.com  
3    http://www.baileytransportationprodinc.com  
4      http://www.kenjeterstoreequipmentinc.com  
..                                          ...  
100                  http://www.maccanidelp.com  
101               http://www.unitedoilcoinc.com  
102          http://www.fioruccifoodsusainc.com  
103             http://www.paganophilipgesq.com  
104     http://www.affiliatedwithtravelodge.com  

[105 rows x 13 columns]