In [1]:
# Multiple Linear Regression

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
dataset = pd.read_csv('employee.csv')

X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values

#Dealing with categorical variables
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import make_column_transformer
onehotencoder = make_column_transformer((OneHotEncoder(), [0]), remainder='passthrough')
X = onehotencoder.fit_transform(X)


print(X)

[[1.0 0.0 0.0 2300 0 1.1]
 [0.0 1.0 0.0 2100 1 1.3]
 [1.0 0.0 0.0 2104 2 1.5]
 [0.0 0.0 1.0 1200 1 2.0]
 [0.0 1.0 0.0 1254 2 2.2]
 [0.0 0.0 1.0 1236 1 2.9]
 [1.0 0.0 0.0 1452 2 3.0]
 [0.0 1.0 0.0 1789 1 3.2]
 [0.0 0.0 1.0 1645 1 3.2]
 [0.0 0.0 1.0 1258 0 3.7]
 [0.0 1.0 0.0 1478 3 3.9]
 [1.0 0.0 0.0 1257 2 4.0]
 [1.0 0.0 0.0 1596 1 4.0]
 [0.0 1.0 0.0 1256 2 4.1]
 [0.0 0.0 1.0 1489 3 4.5]
 [1.0 0.0 0.0 1236 3 4.9]
 [0.0 1.0 0.0 2311 2 5.1]
 [0.0 0.0 1.0 2245 3 5.3]
 [1.0 0.0 0.0 2365 1 5.9]
 [1.0 0.0 0.0 1500 3 6.0]
 [0.0 1.0 0.0 1456 2 6.8]
 [0.0 1.0 0.0 1760 1 7.1]
 [0.0 0.0 1.0 2400 4 7.9]
 [1.0 0.0 0.0 2148 3 8.2]
 [0.0 0.0 1.0 1450 2 8.7]
 [0.0 0.0 1.0 1000 4 9.0]
 [0.0 1.0 0.0 1540 3 9.5]
 [1.0 0.0 0.0 1500 2 9.6]
 [0.0 1.0 0.0 3000 4 10.3]
 [0.0 0.0 1.0 2100 3 10.5]]


In [2]:
# Removing the extra dummy variable
X = X[:, 1:]

#Splitting the data into Training Set and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)
                      

#Fitting Multiple Linear Regression to Training Set
from sklearn.linear_model import LinearRegression
mlrObj = LinearRegression()
mlrObj.fit(X_train,y_train)

#Predicting on the Test Set
y_pred = mlrObj.predict(X_test)

#Backward Elimination
import statsmodels.api as sm
X = np.append(arr=np.ones((30,1)).astype(int), values=X, axis=1)

# Convert to a float64
X = X.astype('float64')  # Without this, OLS function errors out

print(X)

[[1.000e+00 0.000e+00 0.000e+00 2.300e+03 0.000e+00 1.100e+00]
 [1.000e+00 1.000e+00 0.000e+00 2.100e+03 1.000e+00 1.300e+00]
 [1.000e+00 0.000e+00 0.000e+00 2.104e+03 2.000e+00 1.500e+00]
 [1.000e+00 0.000e+00 1.000e+00 1.200e+03 1.000e+00 2.000e+00]
 [1.000e+00 1.000e+00 0.000e+00 1.254e+03 2.000e+00 2.200e+00]
 [1.000e+00 0.000e+00 1.000e+00 1.236e+03 1.000e+00 2.900e+00]
 [1.000e+00 0.000e+00 0.000e+00 1.452e+03 2.000e+00 3.000e+00]
 [1.000e+00 1.000e+00 0.000e+00 1.789e+03 1.000e+00 3.200e+00]
 [1.000e+00 0.000e+00 1.000e+00 1.645e+03 1.000e+00 3.200e+00]
 [1.000e+00 0.000e+00 1.000e+00 1.258e+03 0.000e+00 3.700e+00]
 [1.000e+00 1.000e+00 0.000e+00 1.478e+03 3.000e+00 3.900e+00]
 [1.000e+00 0.000e+00 0.000e+00 1.257e+03 2.000e+00 4.000e+00]
 [1.000e+00 0.000e+00 0.000e+00 1.596e+03 1.000e+00 4.000e+00]
 [1.000e+00 1.000e+00 0.000e+00 1.256e+03 2.000e+00 4.100e+00]
 [1.000e+00 0.000e+00 1.000e+00 1.489e+03 3.000e+00 4.500e+00]
 [1.000e+00 0.000e+00 0.000e+00 1.236e+03 3.000e+00 4.9

In [3]:
X_sig = X[:,[0,1,2,3,4,5]]
obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

X_sig = X[:,[0,1,3,4,5]]

obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

X_sig = X[:,[0,1,3,5]]

obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

X_sig = X[:,[0,3,5]]

obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

X_sig = X[:,[0,5]]

obj_OLS = sm.OLS(endog = y, exog = X_sig).fit()
obj_OLS.summary()

#Splitting the data into Training Set and Test Set
X_sig_train, X_sig_test, y_sig_train, y_sig_test = train_test_split(X_sig, y, test_size=0.2,random_state=0)
mlrObj_sig = LinearRegression()
mlrObj_sig.fit(X_sig_train, y_sig_train)

y_sig_pred = mlrObj_sig.predict(X_sig_test)

#Normalizing the features
#from sklearn.preprocessing import StandardScaler
#sc_X = StandardScaler()
#X_train = sc_X.fit_transform(X_train)
#X_test = sc_X.transform(X_test)

In [4]:
import sklearn
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 0.24.1.
